# Generated by Django 5.0.2 on 2024-06-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('KHI', 'Karachi'), ('LHR', 'Lahore'), ('ISB', 'Islamabad'), ('FSD', 'Faisalabad')], max_length=3)),
                ('cnic', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
